package Sistema;

import java.awt.BorderLayout;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;

import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author joset
 */
public final class AgregarC extends javax.swing.JPanel {

    /**
     * Creates new form AgregarC
     */
    DefaultTableModel model;
    String ruta="";
    public AgregarC() {
        initComponents();
        String[] titulos = {"ID", "Caracteristica","Imagen"};
        model = new DefaultTableModel(null, titulos) {
            @Override
            public boolean isCellEditable(int row, int column) {
                if (column == 1) {
                    return true;
                } else {
                    return false;
                }
            }

        };
        tblcar.setModel(model);
        tblcar.setEditingRow(0);
        tblcar.setEditingRow(1);
        tblcar.setEditingRow(2);

        mostrarDatos();
        limpiar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Fondo();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCara = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblimg = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtimg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblcar = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        bAgregar = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(706, 449));
        setMinimumSize(new java.awt.Dimension(706, 449));
        setPreferredSize(new java.awt.Dimension(706, 449));

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255,80));

        txtCara.setColumns(20);
        txtCara.setRows(5);
        jScrollPane1.setViewportView(txtCara);

        jLabel1.setText("ID:");

        jLabel2.setText("Caracteristicas:");

        txtID.setEditable(false);
        txtID.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtID.setOpaque(true);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Seleccionar imagen");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtimg.setEditable(false);
        txtimg.setBackground(new java.awt.Color(255, 255, 255));
        txtimg.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("AGREGAR CARACTERISTICAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtimg, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblimg, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtimg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255,90));

        tblcar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        tblcar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblcar);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bAgregar.setForeground(new java.awt.Color(90, 90, 90));
        bAgregar.setText("Agregar");
        bAgregar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        bAgregar.setContentAreaFilled(false);
        bAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bAgregarMouseEntered(evt);
            }
        });
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        bEditar.setForeground(new java.awt.Color(102, 102, 102));
        bEditar.setText("Editar");
        bEditar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        bEditar.setContentAreaFilled(false);
        bEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bEditarMouseEntered(evt);
            }
        });
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        bBorrar.setForeground(new java.awt.Color(102, 102, 102));
        bBorrar.setText("Borrar");
        bBorrar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        bBorrar.setContentAreaFilled(false);
        bBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bBorrarMouseEntered(evt);
            }
        });
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        bCancelar.setForeground(new java.awt.Color(102, 102, 102));
        bCancelar.setText("Cancelar");
        bCancelar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        bCancelar.setContentAreaFilled(false);
        bCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bCancelarMouseEntered(evt);
            }
        });
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(bAgregar)
                        .addGap(29, 29, 29)
                        .addComponent(bEditar)
                        .addGap(27, 27, 27)
                        .addComponent(bBorrar)
                        .addGap(30, 30, 30)
                        .addComponent(bCancelar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelarMouseEntered
        // TODO add your handling code here:
        bCancelar.setForeground(new java.awt.Color(254, 254, 254));
        bCancelar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_bCancelarMouseEntered

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        // TODO add your handling code here:
        conexion con = new conexion();
        AMarinos am = recuperarDatosGUI();
        if (txtID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Registro no seleccionado", "Error", 0);
        } else {
            String sql = String.format("DELETE FROM AnimalesCara WHERE ID=%d", am.getID());
            con.ejecutarSentenciaSQL(sql);
            JOptionPane.showMessageDialog(null, "Borrado correctamente", "Borrado", 1);
            limpiar();
            mostrarDatos();
        }
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bBorrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBorrarMouseEntered
        // TODO add your handling code here:
        bBorrar.setForeground(new java.awt.Color(254, 254, 254));
        bBorrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_bBorrarMouseEntered

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        // TODO add your handling code here:
        if (txtCara.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Valores vacios", "Error", 0);
        } else {
            conexion con = new conexion();
            AMarinos am = recuperarDatosGUI();
            String sql = String.format("UPDATE AnimalesCara SET Caracteristica='%s' WHERE ID=%d", am.getCaracteristicas(), am.getID());
            con.ejecutarSentenciaSQL(sql);
            JOptionPane.showMessageDialog(null, "Editado correctamente", "Edicion", 1);
            mostrarDatos();
            limpiar();
        }

    }//GEN-LAST:event_bEditarActionPerformed

    private void bEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditarMouseEntered
        // TODO add your handling code here:
        bEditar.setForeground(new java.awt.Color(254, 254, 254));
        bEditar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_bEditarMouseEntered

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        // TODO add your handling code here:
        if (txtCara.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Valores vacios", "Error", 0);
        } else {
            if (ruta.equals("")) {
                txtimg.setText("C:/Users/joset/OneDrive/Documentos/NetBeansProjects/Sistema E/src/image/nodis.jpg");
            }
            conexion con = new conexion();
            AMarinos am = recuperarDatosGUI();
            String sql = String.format("INSERT INTO AnimalesCara (ID,Caracteristica,Imagen)"
                    + "VALUES(null,'%s','%s')", am.getCaracteristicas(),am.getImg());
            con.ejecutarSentenciaSQL(sql);
            JOptionPane.showMessageDialog(null, "Agregado correctamente", "Insersion", 1);
            mostrarDatos();
            limpiar();
        }
    }//GEN-LAST:event_bAgregarActionPerformed

    private void bAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAgregarMouseEntered
        // TODO add your handling code here:
        bAgregar.setForeground(new java.awt.Color(254, 254, 254));
        bAgregar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_bAgregarMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        InterfazE ie = new InterfazE();
        ie.setSize(709, 449);
        ie.setLocation(0, 0);
        jPanel1.removeAll();
        jPanel1.add(ie, BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
        bAgregar.setForeground(new java.awt.Color(90, 90, 90));
        bAgregar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        bEditar.setForeground(new java.awt.Color(90, 90, 90));
        bEditar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        bBorrar.setForeground(new java.awt.Color(90, 90, 90));
        bBorrar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        bCancelar.setForeground(new java.awt.Color(90, 90, 90));
        bCancelar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

    }//GEN-LAST:event_jPanel1MouseEntered

    private void tblcarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcarMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();
            txtID.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            txtCara.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
            txtimg.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
            Image foto = getToolkit().getImage(txtimg.getText());
            foto = foto.getScaledInstance(lblimg.getWidth(), lblimg.getHeight(), 1);
            lblimg.setIcon(new ImageIcon(foto));
            bAgregar.setEnabled(false);
            bEditar.setEnabled(true);
            bBorrar.setEnabled(true);
        }
    }//GEN-LAST:event_tblcarMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser jf = new JFileChooser();
        FileNameExtensionFilter ef = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        File r = new File("C:/Users/joset/Downloads/");
        jf.setCurrentDirectory(r);
        jf.setFileFilter(ef);
        jf.setDialogTitle("Abrir Archivo");
        if (jf.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            ruta = jf.getSelectedFile().getAbsolutePath();
            File file = jf.getSelectedFile();
            txtimg.setText(String.valueOf(file));
            Image foto = getToolkit().getImage(txtimg.getText());
            foto = foto.getScaledInstance(lblimg.getWidth(), lblimg.getHeight(), Image.SCALE_DEFAULT);
            lblimg.setIcon(new ImageIcon(foto));
            //Image img = new ImageIcon(ruta).getImage();
            //ImageIcon micon = new ImageIcon(img.getScaledInstance(imglabel.getWidth(), imglabel.getHeight(), 0));
            //imglabel.setIcon(micon);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void limpiar(){
        txtID.setText("");
        txtCara.setText("");
        txtimg.setText("");
        bAgregar.setEnabled(true);
        bEditar.setEnabled(false);
        bBorrar.setEnabled(false);
        foto();
    }
    public void foto() {
        Image foto = getToolkit().getImage("C:/Users/joset/OneDrive/Documentos/NetBeansProjects/Sistema E/src/image/nodis.jpg");
        foto = foto.getScaledInstance(140, 140, Image.SCALE_SMOOTH);
        lblimg.setIcon(new ImageIcon(foto));
    }
    public AMarinos recuperarDatosGUI() {
        AMarinos am = new AMarinos();
        int ID = (txtID.getText().isEmpty() ? 0 : Integer.parseInt(txtID.getText()));
        am.setID(ID);
        am.setCaracteristicas(txtCara.getText());
        am.setImg(txtimg.getText());

        return am;
    }

    public void mostrarDatos() {
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        conexion con = new conexion();
        try {
            ResultSet res = con.consultaReg("SELECT * FROM AnimalesCara");
            while (res.next()) {
                Object[] user = {res.getString("ID"), res.getString("Caracteristica"),res.getString("Imagen")};
                model.addRow(user);
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bEditar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblimg;
    private javax.swing.JTable tblcar;
    private javax.swing.JTextArea txtCara;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtimg;
    // End of variables declaration//GEN-END:variables
    class Fondo extends JPanel {

        private Image im;

        public void paint(Graphics g) {
            im = new ImageIcon(getClass().getResource("/image/fondo.jpg")).getImage();
            g.drawImage(im, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
